# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-09 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='domain_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
