# Generated by Django 2.1.5 on 2019-01-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190115_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(max_length=50),
        ),
    ]
