# Generated by Django 2.1.5 on 2019-01-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190115_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='arecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=50)),
                ('redirect_url', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('ssl_cert', models.TextField(blank=True, null=True)),
                ('pub_key', models.TextField(blank=True, null=True)),
                ('chain_key', models.TextField(blank=True, null=True)),
                ('updated_date', models.CharField(max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
