# Generated by Django 2.1.5 on 2019-01-18 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_arecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
