# Generated by Django 2.1.5 on 2019-01-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='arecord',
            name='protocol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
